export default {
  LOGIN_ERROR: 'LOGIN_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_ERROR: 'REGISTER_ERROR',
  ISBN_ERROR: 'ISBN_ERROR',
  REVIEW_ISBN_NOT_FOUND: 'REVIEW_ISBN_NOT_FOUND',
  SAVE_ERROR: 'SAVE_ERROR',
  LOAD_BOOKS_ERROR: 'LOAD_BOOKS_ERROR',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  LOAD_RATINGS_ERROR: 'LOAD_RATINGS_ERROR',
  SAVE_RATING_ERROR: 'SAVE_RATING_ERROR',
  LOAD_USER_LIST_ERROR: 'LOAD_USER_LIST_ERROR'
};
